export { default as Navbar } from "./Navbar"
export { default as Card } from "./Card"
export { default as Membran } from "./Membran"
export { default as Tamco } from "./Tamco"
export { default as Footer } from "./Footer"